<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's "Systematic
  French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/DefInjected/**/*.xml key. There is no Mod/Languages/English
  folder: English text is the game's native fallback, read directly from Mod/Defs by the same
  dotted path DefInjected uses (label/description/jobString, and a list item addressed by the
  text of its own <label>, such as tools.head.label). The original mod (2blockdude,
  HendraGradeWood) was authored in English, so the Original column equals English throughout;
  said once here rather than on every row (mirrors FoodCourt/_tools/Generate-FrenchReview.ps1,
  the reference implementation this is adapted from).
.EXAMPLE
  pwsh -NoProfile -File _tools/Generate-FrenchReview.ps1
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

# key looks like "DefName.field" or "DefName.tools.head.label": a non-numeric list segment
# addresses the <li> whose own <label> text equals that segment (RimWorld's own convention for
# injecting into an unnamed list item), not a numeric index — this mod has no numeric list keys.
function Resolve-DefField($defsRoot, [string]$key) {
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defNamedCache) {
        $script:defNamedCache = @{} # Name= attribute -> node, for ParentName resolution
        $script:defByDefName = @{}
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            foreach ($n in $x.SelectNodes('//*[@Name]')) { $script:defNamedCache[$n.GetAttribute('Name')] = $n }
            foreach ($n in $x.SelectNodes('//*[defName]')) { if (-not $script:defByDefName.ContainsKey($n.defName)) { $script:defByDefName[$n.defName] = $n } }
        }
    }
    if (-not $script:defCache.ContainsKey($defName)) { $script:defCache[$defName] = $script:defByDefName[$defName] }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    for ($i = 0; $i -lt $rest.Count; $i++) {
        $p = $rest[$i]
        if ($null -eq $cur) { return $null }
        # A field not declared on the concrete def may live on its abstract ParentName chain
        # (e.g. tools, inherited from BaseDustBunny): walk it before giving up.
        $probe = $cur
        $guard = 0
        $hit = $null
        while ($probe -and $guard++ -lt 20) {
            if ($p -match '^\d+$') { $hit = 'numeric'; break }
            $direct = $probe.SelectSingleNode($p)
            if ($direct) { $hit = $direct; break }
            $named = $probe.SelectSingleNode("*[label='$p']")
            if ($named) { $hit = $named; break }
            $parentName = $probe.GetAttribute('ParentName')
            $probe = if ($parentName -and $script:defNamedCache.ContainsKey($parentName)) { $script:defNamedCache[$parentName] } else { $null }
        }
        if ($null -eq $hit) { return $null }
        if ($hit -eq 'numeric') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $hit
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** The source mod (2blockdude, HendraGradeWood)")
[void]$out.AppendLine("was authored in English; there is no other-language original anywhere in this repository or")
[void]$out.AppendLine("the source mod (ATTRIBUTION.md). No Mod/Languages/English folder exists either: English is the")
[void]$out.AppendLine("game's native fallback, read here straight from Mod/Defs.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree, packageId nelim.dustbunnies.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $defsRoot $key
        $en = $orig
        if ($null -eq $orig) { $orig = '*(not found - check by hand)*'; $en = '*(not found - check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
